# Generated by Django 2.0.2 on 2021-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_emails_savedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='subject',
            field=models.CharField(default='Subject', max_length=200),
            preserve_default=False,
        ),
    ]
